### ISSUE TITLE
Web server and queue able to handle docker image builds

### ISSUE THREAD

**Issue by williams-jack** [CodeGrade/orca#35]
Orca's ability to grade assignments in custom containers is based on the following fundamentals:
1. The web server should be able to support building custom images given a Dockerfile.
2. The grading queue should not send workers grading jobs whose images are not ready yet.

Additionally, the server should have a clean up protocol to ensure stale images do not take up resources unnecessarily.

**Comment by blerner** [comment]
Is this moot and closable now?

**Comment by williams-jack** [comment]
Yup, will close it now
