### ISSUE TITLE
Vulnerability in `react-scripts`

### ISSUE THREAD

**Issue by williams-jack** [CodeGrade/orca#4]
The module `react-scripts` currently has a severe vulnerability due to a series of dependencies that point to an issue in the `nth-check` version used by the package.

[Click here for more information](https://github.com/facebook/create-react-app/issues/11647); should be fixed in a patch at some point in the future.

**Comment by NitinGola** [comment]
Any idea when the fix for nth-check vulnerability will be released?

**Comment by blerner** [comment]
Is this moot?  I don't see this module in our dependencies?

**Comment by williams-jack** [comment]
This should be fine now yes, if nothing else React will have certainly fixed it by now
